name: Publish to crates.io

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    # skip prereleases like v1.2.3-rc.1
    if: ${{ !contains(github.ref_name, '-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Verify tag matches Cargo.toml version
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF_NAME#v}"
          CARGO_V=$(grep '^version\s*=\s*"' Cargo.toml | head -n1 | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Tag: $TAG  | Cargo.toml: $CARGO_V"
          [ "$TAG" = "$CARGO_V" ] || { echo "::error ::Tag ($TAG) != Cargo.toml ($CARGO_V)"; exit 1; }

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
